<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE root [
<!ELEMENT root (match*)>
<!ELEMENT match (word*)>
<!ATTLIST match characters CDATA #REQUIRED>
<!ATTLIST match count CDATA #REQUIRED>
<!ATTLIST match name (yes|no) "no">
<!ELEMENT word (#PCDATA)>
]>
<root>
<match characters='黒' count='24922' name='yes'><word>黒</word><word>黒い</word><word>黒む</word></match>
<match characters='白' count='24699' name='yes'><word>白</word><word>白い</word><word>白む</word></match>
<match characters='参考図' count='2338'><word>参考図</word></match>
<match characters='解説者' count='1590'><word>解説者</word></match>
<match characters='名人' count='1483' name='yes'><word>名人</word></match>
<match characters='手' count='1368' name='yes'><word>手</word></match>
<match characters='張' count='1181' name='yes'><word>張</word><word>張る</word></match>
<match characters='九段' count='1109' name='yes'><word>九段</word></match>
<match characters='分' count='1059' name='yes'><word>分</word><word>分つ</word><word>分る</word></match>
<match characters='打' count='1037'><word>打</word><word>打つ</word></match>
<match characters='中央' count='1025' name='yes'><word>中央</word></match>
<match characters='下辺' count='1021' name='yes'><word>下辺</word></match>
<match characters='右辺' count='1001'><word>右辺</word></match>
<match characters='小林' count='959' name='yes'></match>
<match characters='上辺' count='958' name='yes'><word>上辺</word></match>
<match characters='挑戦者' count='953'><word>挑戦者</word></match>
<match characters='出' count='939' name='yes'><word>出</word><word>出す</word><word>出る</word></match>
<match characters='坂井' count='918' name='yes'></match>
<match characters='実戦' count='906'><word>実戦</word></match>
<match characters='検討' count='879'><word>検討</word></match>
<match characters='局' count='868' name='yes'><word>局</word></match>
<match characters='左辺' count='864'><word>左辺</word></match>
<match characters='目' count='863' name='yes'><word>目</word><word>目す</word></match>
<match characters='見' count='826' name='yes'><word>見</word><word>見す</word><word>見る</word></match>
<match characters='思' count='819' name='yes'><word>思う</word></match>
<match characters='形勢' count='798'><word>形勢</word></match>
<match characters='高尾' count='797' name='yes'></match>
<match characters='決め' count='777'><word>決め</word><word>決める</word></match>
<match characters='形' count='761' name='yes'><word>形</word></match>
<match characters='趙' count='722' name='yes'></match>
<match characters='生き' count='705'><word>生き</word><word>生きる</word></match>
<match characters='山田' count='699' name='yes'></match>
<match characters='切り' count='693'><word>切り</word></match>
<match characters='攻め' count='677'><word>攻め</word><word>攻める</word></match>
<match characters='碁' count='677'><word>碁</word></match>
<match characters='勝' count='673' name='yes'><word>勝</word><word>勝つ</word><word>勝る</word></match>
<match characters='戦' count='671' name='yes'><word>戦</word><word>戦う</word><word>戦く</word><word>戦ぐ</word></match>
<match characters='王' count='666' name='yes'><word>王</word></match>
<match characters='取' count='661' name='yes'><word>取</word><word>取る</word></match>
<match characters='図' count='658' name='yes'><word>図</word><word>図る</word></match>
<match characters='考え' count='637'><word>考え</word><word>考える</word></match>
<match characters='以下' count='636'><word>以下</word></match>
<match characters='勝ち' count='624'><word>勝ち</word></match>
<match characters='井山' count='598' name='yes'></match>
<match characters='負け' count='594'><word>負け</word><word>負ける</word></match>
<match characters='一手' count='591'><word>一手</word></match>
<match characters='地' count='588' name='yes'><word>地</word></match>
<match characters='勝負' count='578' name='yes'><word>勝負</word></match>
<match characters='対局' count='570'><word>対局</word></match>
<match characters='山下' count='565' name='yes'></match>
<match characters='右下' count='537' name='yes'><word>右下</word></match>
<match characters='切' count='532'><word>切</word><word>切る</word></match>
<match characters='譜' count='532'><word>譜</word></match>
<match characters='結城' count='530' name='yes'></match>
<match characters='右上' count='529'><word>右上</word></match>
<match characters='後' count='525' name='yes'><word>後</word></match>
<match characters='左下' count='517'><word>左下</word></match>
<match characters='分か' count='508'><word>分かつ</word><word>分かる</word></match>
<match characters='受け' count='490'><word>受け</word><word>受ける</word></match>
<match characters='続いて' count='489'><word>続いて</word></match>
<match characters='先手' count='483'><word>先手</word></match>
<match characters='依田' count='480' name='yes'></match>
<match characters='今村' count='476' name='yes'></match>
<match characters='左上' count='473'><word>左上</word></match>
<match characters='判断' count='468'><word>判断</word></match>
<match characters='見え' count='456'><word>見え</word><word>見える</word></match>
<match characters='悪' count='446' name='yes'><word>悪</word><word>悪い</word><word>悪む</word></match>
<match characters='残' count='442' name='yes'><word>残</word><word>残す</word><word>残る</word></match>
<match characters='解説' count='436'><word>解説</word></match>
<match characters='羽根' count='431' name='yes'><word>羽根</word></match>
<match characters='室' count='428' name='yes'><word>室</word></match>
<match characters='眼形' count='428'><word>眼形</word></match>
<match characters='本局' count='424'><word>本局</word></match>
<match characters='陣' count='423' name='yes'><word>陣</word></match>
<match characters='小県' count='420' name='yes'></match>
<match characters='林' count='410' name='yes'><word>林</word></match>
<match characters='石' count='409' name='yes'><word>石</word></match>
<match characters='溝上' count='401' name='yes'></match>
<match characters='入' count='398' name='yes'><word>入</word><word>入る</word></match>
<match characters='思い' count='396'><word>思い</word></match>
<match characters='棋士' count='383'><word>棋士</word></match>
<match characters='時間' count='379' name='yes'><word>時間</word></match>
<match characters='構え' count='378'><word>構え</word><word>構える</word></match>
<match characters='前' count='373' name='yes'><word>前</word></match>
<match characters='厚' count='372' name='yes'><word>厚</word><word>厚い</word></match>
<match characters='薄' count='360' name='yes'><word>薄</word><word>薄い</word></match>
<match characters='敗' count='356'><word>敗</word><word>敗る</word></match>
<match characters='打っ' count='354'><word>打っ</word></match>
<match characters='進行' count='354' name='yes'><word>進行</word></match>
<match characters='狙い' count='352'><word>狙い</word></match>
<match characters='盤' count='351' name='yes'><word>盤</word></match>
<match characters='隅' count='351' name='yes'><word>隅</word></match>
<match characters='大き' count='348'><word>大き</word><word>大きい</word></match>
<match characters='名人戦' count='346'><word>名人戦</word></match>
<match characters='石田' count='346' name='yes'></match>
<match characters='大きく' count='339'><word>大きく</word></match>
<match characters='小松' count='339' name='yes'><word>小松</word></match>
<match characters='難し' count='337'><word>難し</word><word>難しい</word></match>
<match characters='当然' count='331'><word>当然</word></match>
<match characters='方' count='330' name='yes'><word>方</word></match>
<match characters='狙' count='330'><word>狙う</word></match>
<match characters='子' count='326' name='yes'><word>子</word></match>
<match characters='分の' count='321'><word>分の</word></match>
<match characters='戦い' count='315'><word>戦い</word></match>
<match characters='上' count='312' name='yes'><word>上</word><word>上す</word><word>上る</word></match>
<match characters='打たれ' count='310'><word>打たれる</word></match>
<match characters='模様' count='310'><word>模様</word></match>
<match characters='交換' count='302'><word>交換</word></match>
<match characters='感じ' count='296'><word>感じ</word><word>感じる</word></match>
<match characters='記者' count='296'><word>記者</word></match>
<match characters='厳し' count='295'><word>厳しい</word></match>
<match characters='向か' count='294'><word>向かう</word></match>
<match characters='声' count='294' name='yes'><word>声</word></match>
<match characters='変化' count='293'><word>変化</word></match>
<match characters='黄' count='293' name='yes'><word>黄</word></match>
<match characters='厚み' count='289' name='yes'><word>厚み</word></match>
<match characters='好手' count='279'><word>好手</word></match>
<match characters='午後' count='275'><word>午後</word></match>
<match characters='中' count='271' name='yes'><word>中</word><word>中る</word></match>
<match characters='人' count='271' name='yes'><word>人</word></match>
<match characters='点' count='270' name='yes'><word>点</word><word>点く</word><word>点す</word><word>点る</word></match>
<match characters='黒地' count='270' name='yes'><word>黒地</word></match>
<match characters='回' count='269' name='yes'><word>回</word><word>回す</word><word>回る</word></match>
<match characters='備え' count='268'><word>備え</word><word>備える</word></match>
<match characters='姿' count='266' name='yes'><word>姿</word></match>
<match characters='定石' count='265' name='yes'><word>定石</word></match>
<match characters='年' count='265' name='yes'><word>年</word></match>
<match characters='最後' count='265'><word>最後</word></match>
<match characters='優勢' count='263'><word>優勢</word></match>
<match characters='時' count='263' name='yes'><word>時</word></match>
<match characters='大きな' count='258'><word>大きな</word></match>
<match characters='序盤' count='258'><word>序盤</word></match>
<match characters='選' count='252' name='yes'><word>選</word><word>選ぶ</word><word>選る</word></match>
<match characters='得' count='251' name='yes'><word>得</word><word>得る</word></match>
<match characters='終わ' count='249'><word>終わる</word></match>
<match characters='白地' count='247' name='yes'><word>白地</word></match>
<match characters='手順' count='246'><word>手順</word></match>
<match characters='筋' count='243' name='yes'><word>筋</word></match>
<match characters='両者' count='240'><word>両者</word></match>
<match characters='好' count='238' name='yes'><word>好</word><word>好い</word><word>好く</word><word>好む</word></match>
<match characters='味' count='236'><word>味</word></match>
<match characters='感想' count='236'><word>感想</word></match>
<match characters='河野' count='236' name='yes'></match>
<match characters='差' count='235'><word>差</word><word>差す</word></match>
<match characters='盤面' count='235'><word>盤面</word></match>
<match characters='取り' count='233'><word>取り</word></match>
<match characters='連絡' count='233'><word>連絡</word></match>
<match characters='予想' count='232'><word>予想</word></match>
<match characters='逃げ' count='232'><word>逃げ</word><word>逃げる</word></match>
<match characters='コウ材' count='231'><word>コウ材</word></match>
<match characters='流れ' count='231'><word>流れ</word><word>流れる</word></match>
<match characters='多' count='226' name='yes'><word>多</word><word>多い</word></match>
<match characters='行' count='224' name='yes'><word>行</word><word>行う</word><word>行く</word><word>行る</word></match>
<match characters='手段' count='221'><word>手段</word></match>
<match characters='違' count='221' name='yes'><word>違う</word></match>
<match characters='十分' count='220'><word>十分</word></match>
<match characters='省' count='219' name='yes'><word>省</word><word>省く</word></match>
<match characters='攻め合い' count='218'><word>攻め合い</word></match>
<match characters='問題' count='217'><word>問題</word></match>
<match characters='心配' count='217'><word>心配</word></match>
<match characters='抜' count='216'><word>抜く</word></match>
<match characters='損' count='216' name='yes'><word>損</word><word>損う</word></match>
<match characters='分かれ' count='215'><word>分かれ</word><word>分かれる</word></match>
<match characters='苦し' count='215'><word>苦しい</word><word>苦しむ</word></match>
<match characters='局面' count='213'><word>局面</word></match>
<match characters='終局' count='213'><word>終局</word></match>
<match characters='仕掛け' count='211'><word>仕掛け</word><word>仕掛ける</word></match>
<match characters='戻' count='211'><word>戻す</word><word>戻る</word></match>
<match characters='記者室' count='211'><word>記者室</word></match>
<match characters='切ら' count='210'><word>切らす</word></match>
<match characters='以上' count='207'><word>以上</word></match>
<match characters='迫' count='205' name='yes'><word>迫る</word></match>
<match characters='前に' count='204'><word>前に</word></match>
<match characters='敗着' count='202'><word>敗着</word></match>
<match characters='長考' count='202'><word>長考</word></match>
<match characters='単に' count='198'><word>単に</word></match>
<match characters='休憩' count='197'><word>休憩</word></match>
<match characters='残り' count='197'><word>残り</word></match>
<match characters='片岡' count='196' name='yes'></match>
<match characters='続' count='196' name='yes'><word>続</word><word>続く</word><word>続ぐ</word></match>
<match characters='先に' count='194'><word>先に</word></match>
<match characters='半目' count='194'><word>半目</word></match>
<match characters='急所' count='193'><word>急所</word></match>
<match characters='大' count='191' name='yes'><word>大</word></match>
<match characters='同じ' count='189'><word>同じ</word><word>同じる</word></match>
<match characters='成立' count='189' name='yes'><word>成立</word><word>成立つ</word></match>
<match characters='棋聖' count='189'><word>棋聖</word></match>
<match characters='相手' count='189'><word>相手</word></match>
<match characters='守' count='188' name='yes'><word>守</word><word>守る</word></match>
<match characters='考慮' count='187'><word>考慮</word></match>
<match characters='逆転' count='187'><word>逆転</word></match>
<match characters='不満' count='186'><word>不満</word></match>
<match characters='始ま' count='186'><word>始まる</word></match>
<match characters='嫌' count='183'><word>嫌</word><word>嫌う</word></match>
<match characters='立会人' count='179'><word>立会人</word></match>
<match characters='注目' count='178'><word>注目</word></match>
<match characters='投了' count='177'><word>投了</word></match>
<match characters='入り' count='176'><word>入り</word></match>
<match characters='冷静' count='176'><word>冷静</word></match>
<match characters='利' count='176' name='yes'><word>利</word><word>利く</word></match>
<match characters='反発' count='176'><word>反発</word></match>
<match characters='栩' count='176' name='yes'></match>
<match characters='頭' count='176' name='yes'><word>頭</word></match>
<match characters='利か' count='175'><word>利かす</word></match>
<match characters='場面' count='175'><word>場面</word></match>
<match characters='彦坂' count='175' name='yes'></match>
<match characters='日本棋院' count='173'><word>日本棋院</word></match>
<match characters='に対して' count='170'><word>に対して</word></match>
<match characters='手を抜' count='170'><word>手を抜く</word></match>
<match characters='展開' count='169'><word>展開</word></match>
<match characters='歳' count='169' name='yes'><word>歳</word></match>
<match characters='抜き' count='168'><word>抜き</word></match>
<match characters='生きる' count='168'><word>生きる</word></match>
<match characters='気' count='167' name='yes'><word>気</word></match>
<match characters='奪' count='166'><word>奪う</word></match>
<match characters='動' count='165' name='yes'><word>動</word><word>動く</word></match>
<match characters='着手' count='165'><word>着手</word></match>
<match characters='一子' count='164' name='yes'><word>一子</word></match>
<match characters='潘' count='164' name='yes'></match>
<match characters='押し' count='163'><word>押し</word></match>
<match characters='状況' count='163'><word>状況</word></match>
<match characters='止め' count='162'><word>止め</word><word>止める</word></match>
<match characters='解消' count='162'><word>解消</word></match>
<match characters='二子' count='161' name='yes'><word>二子</word></match>
<match characters='逆に' count='161'><word>逆に</word></match>
<match characters='三々' count='160'><word>三々</word></match>
<match characters='読み' count='160'><word>読み</word></match>
<match characters='自信' count='159' name='yes'><word>自信</word></match>
<match characters='大石' count='158' name='yes'><word>大石</word></match>
<match characters='捨て' count='158'><word>捨てる</word></match>
<match characters='見合い' count='158'><word>見合い</word></match>
<match characters='多く' count='157'><word>多く</word></match>
<match characters='小さ' count='157'><word>小さ</word><word>小さい</word></match>
<match characters='後悔' count='156'><word>後悔</word></match>
<match characters='意識' count='156'><word>意識</word></match>
<match characters='決ま' count='156'><word>決まる</word></match>
<match characters='一局' count='155'><word>一局</word></match>
<match characters='気がつ' count='155'><word>気がつく</word></match>
<match characters='確保' count='155'><word>確保</word></match>
<match characters='実は' count='154'><word>実は</word></match>
<match characters='瞬間' count='154'><word>瞬間</word></match>
<match characters='利かし' count='153'><word>利かし</word></match>
<match characters='囲' count='153' name='yes'><word>囲う</word><word>囲む</word></match>
<match characters='打ち込' count='153'><word>打ち込む</word></match>
<match characters='実利' count='152' name='yes'><word>実利</word></match>
<match characters='取れ' count='151'><word>取れる</word></match>
<match characters='抵抗' count='151'><word>抵抗</word></match>
<match characters='最近' count='151'><word>最近</word></match>
<match characters='絶好' count='151'><word>絶好</word></match>
<match characters='一つ' count='150'><word>一つ</word></match>
<match characters='普通' count='150'><word>普通</word></match>
<match characters='半' count='148' name='yes'><word>半</word></match>
<match characters='少し' count='148'><word>少し</word></match>
<match characters='気合' count='148'><word>気合</word></match>
<match characters='制' count='147' name='yes'><word>制</word><word>制す</word></match>
<match characters='大矢' count='147' name='yes'></match>
<match characters='封鎖' count='147'><word>封鎖</word></match>
<match characters='思え' count='147'><word>思える</word></match>
<match characters='最終' count='147'><word>最終</word></match>
<match characters='読者' count='146'><word>読者</word></match>
<match characters='対局者' count='145'><word>対局者</word></match>
<match characters='打ち込み' count='145'><word>打ち込み</word></match>
<match characters='止ま' count='145'><word>止まる</word></match>
<match characters='求め' count='145'><word>求め</word><word>求める</word></match>
<match characters='次' count='144' name='yes'><word>次</word><word>次ぐ</word></match>
<match characters='秒読み' count='144'><word>秒読み</word></match>
<match characters='何' count='143' name='yes'><word>何</word></match>
<match characters='期' count='143' name='yes'><word>期</word><word>期す</word></match>
<match characters='珍し' count='143'><word>珍しい</word></match>
<match characters='確かに' count='143'><word>確かに</word></match>
<match characters='勝負手' count='142'><word>勝負手</word></match>
<match characters='必要' count='142'><word>必要</word></match>
<match characters='勝利' count='140' name='yes'><word>勝利</word></match>
<match characters='引' count='140' name='yes'><word>引く</word></match>
<match characters='作戦' count='139'><word>作戦</word></match>
<match characters='語' count='138' name='yes'><word>語</word><word>語る</word></match>
<match characters='強' count='136' name='yes'><word>強</word><word>強い</word></match>
<match characters='簡単' count='136'><word>簡単</word></match>
<match characters='結論' count='136'><word>結論</word></match>
<match characters='間' count='135' name='yes'><word>間</word></match>
<match characters='予定' count='134'><word>予定</word></match>
<match characters='弱' count='134'><word>弱</word><word>弱い</word><word>弱る</word></match>
<match characters='調子' count='134' name='yes'><word>調子</word></match>
<match characters='込' count='134'><word>込む</word></match>
<match characters='可能性' count='133'><word>可能性</word></match>
<match characters='初めて' count='132'><word>初めて</word></match>
<match characters='手厚' count='132'><word>手厚い</word></match>
<match characters='本因坊' count='132' name='yes'><word>本因坊</word></match>
<match characters='私' count='131' name='yes'><word>私</word></match>
<match characters='順に' count='131'><word>順に</word></match>
<match characters='一方' count='130' name='yes'><word>一方</word></match>
<match characters='逃' count='130'><word>逃す</word></match>
<match characters='銘' count='130' name='yes'><word>銘</word></match>
<match characters='悪くな' count='128'><word>悪くなる</word></match>
<match characters='残留' count='128'><word>残留</word></match>
<match characters='気持ち' count='128'><word>気持ち</word></match>
<match characters='落ち' count='128'><word>落ち</word><word>落ちる</word></match>
<match characters='の利' count='127' name='yes'></match>
<match characters='進' count='127' name='yes'><word>進ぶ</word><word>進む</word></match>
<match characters='先生' count='126' name='yes'><word>先生</word></match>
<match characters='今度' count='125' name='yes'><word>今度</word></match>
<match characters='大変' count='125'><word>大変</word></match>
<match characters='書' count='125'><word>書</word><word>書く</word></match>
<match characters='自分' count='125'><word>自分</word></match>
<match characters='名誉' count='124'><word>名誉</word></match>
<match characters='地合い' count='124'><word>地合い</word></match>
<match characters='章' count='124' name='yes'><word>章</word></match>
<match characters='符号' count='124'><word>符号</word></match>
<match characters='位' count='123' name='yes'><word>位</word></match>
<match characters='小林覚' count='123' name='yes'></match>
<match characters='確かめ' count='123'><word>確かめ</word><word>確かめる</word></match>
<match characters='許し' count='123'><word>許し</word></match>
<match characters='完全' count='122'><word>完全</word></match>
<match characters='挑戦' count='122'><word>挑戦</word></match>
<match characters='第１' count='122'><word>第１</word></match>
<match characters='後に' count='121'><word>後に</word></match>
<match characters='手抜き' count='121'><word>手抜き</word></match>
<match characters='三子' count='120' name='yes'><word>三子</word></match>
<match characters='出し' count='120' name='yes'><word>出し</word></match>
<match characters='生じ' count='120'><word>生じる</word></match>
<match characters='関西棋院' count='120' name='yes'><word>関西棋院</word></match>
<match characters='内田' count='119' name='yes'></match>
<match characters='困' count='119'><word>困る</word></match>
<match characters='天元' count='119' name='yes'><word>天元</word></match>
<match characters='意外' count='119' name='yes'><word>意外</word></match>
<match characters='気にな' count='119'><word>気になる</word></match>
<match characters='迎え' count='119'><word>迎え</word><word>迎える</word></match>
<match characters='連勝' count='119'><word>連勝</word></match>
<match characters='与え' count='117'><word>与え</word><word>与える</word></match>
<match characters='昨年' count='117'><word>昨年</word></match>
<match characters='決行' count='117'><word>決行</word></match>
<match characters='聞' count='117' name='yes'><word>聞く</word></match>
<match characters='ハネ出し' count='116'><word>ハネ出し</word></match>
<match characters='押' count='116' name='yes'><word>押す</word></match>
<match characters='反省' count='115'><word>反省</word></match>
<match characters='待' count='115'><word>待つ</word></match>
<match characters='相場' count='114' name='yes'><word>相場</word></match>
<match characters='出切り' count='113'><word>出切り</word></match>
<match characters='指摘' count='113'><word>指摘</word></match>
<match characters='消し' count='113'><word>消し</word></match>
<match characters='理屈' count='113'><word>理屈</word></match>
<match characters='相当' count='113' name='yes'><word>相当</word></match>
<match characters='見せ' count='113'><word>見せる</word></match>
<match characters='有力' count='112'><word>有力</word></match>
<match characters='第' count='112'><word>第</word></match>
<match characters='入れ' count='111'><word>入れ</word><word>入れる</word></match>
<match characters='悪手' count='111'><word>悪手</word></match>
<match characters='意見' count='111'><word>意見</word></match>
<match characters='十' count='110' name='yes'><word>十</word></match>
<match characters='大場' count='109' name='yes'><word>大場</word></match>
<match characters='強い' count='109'><word>強いる</word></match>
<match characters='後手' count='109'><word>後手</word></match>
<match characters='一団' count='108'><word>一団</word></match>
<match characters='以降' count='108'><word>以降</word></match>
<match characters='布石' count='108'><word>布石</word></match>
<match characters='決断' count='108'><word>決断</word></match>
<match characters='勢い' count='107'><word>勢い</word></match>
<match characters='強手' count='107'><word>強手</word></match>
<match characters='用意' count='107'><word>用意</word></match>
<match characters='七番' count='106' name='yes'></match>
<match characters='夕食' count='106'><word>夕食</word></match>
<match characters='封じ手' count='106'><word>封じ手</word></match>
<match characters='正し' count='106'><word>正しい</word></match>
<match characters='読' count='106' name='yes'><word>読む</word></match>
<match characters='連敗' count='106'><word>連敗</word></match>
<match characters='出切' count='105'><word>出切る</word></match>
<match characters='十二' count='105' name='yes'><word>十二</word></match>
<match characters='四' count='105' name='yes'><word>四</word></match>
<match characters='激し' count='105'><word>激しい</word></match>
<match characters='甘' count='105' name='yes'><word>甘い</word></match>
<match characters='二' count='104' name='yes'><word>二</word></match>
<match characters='応じ' count='104'><word>応じる</word></match>
<match characters='換わ' count='104'><word>換わる</word></match>
<match characters='本' count='104' name='yes'><word>本</word></match>
<match characters='趙治勲' count='104' name='yes'></match>
<match characters='長' count='104' name='yes'><word>長</word><word>長い</word></match>
<match characters='２日' count='104'><word>２日</word></match>
<match characters='一着' count='103'><word>一着</word></match>
<match characters='二つ' count='103'><word>二つ</word></match>
<match characters='評判' count='103'><word>評判</word></match>
<match characters='譲' count='103' name='yes'><word>譲る</word></match>
<match characters='金' count='103' name='yes'><word>金</word></match>
<match characters='力' count='102' name='yes'><word>力</word><word>力む</word></match>
<match characters='絶対' count='102'><word>絶対</word></match>
<match characters='持' count='101' name='yes'><word>持つ</word></match>
<match characters='違い' count='101'><word>違い</word></match>
<match characters='決め手' count='100'><word>決め手</word></match>
<match characters='生か' count='100'><word>生かす</word><word>生かる</word></match>
<match characters='細か' count='100'><word>細か</word><word>細かい</word></match>
<match characters='選択' count='100'><word>選択</word></match>
<match characters='不思議' count='99' name='yes'><word>不思議</word></match>
<match characters='広げ' count='99'><word>広げる</word></match>
<match characters='断' count='99' name='yes'><word>断</word><word>断つ</word><word>断る</word></match>
<match characters='次の一手' count='99'><word>次の一手</word></match>
<match characters='話' count='99' name='yes'><word>話</word><word>話す</word></match>
<match characters='道' count='99' name='yes'><word>道</word></match>
<match characters='今期' count='98'><word>今期</word></match>
<match characters='占め' count='98'><word>占める</word></match>
<match characters='楽しみ' count='98'><word>楽しみ</word></match>
<match characters='気づ' count='98'><word>気づく</word></match>
<match characters='費や' count='98'><word>費やす</word></match>
<match characters='三村' count='97' name='yes'></match>
<match characters='動か' count='96'><word>動かす</word></match>
<match characters='工夫' count='96'><word>工夫</word></match>
<match characters='東京' count='96' name='yes'><word>東京</word></match>
<match characters='構想' count='96'><word>構想</word></match>
<match characters='結果' count='96' name='yes'><word>結果</word></match>
<match characters='雰囲気' count='96'><word>雰囲気</word></match>
<match characters='余裕' count='95'><word>余裕</word></match>
<match characters='十一' count='95' name='yes'><word>十一</word></match>
<match characters='肩' count='95' name='yes'><word>肩</word></match>
<match characters='近' count='95' name='yes'><word>近い</word></match>
<match characters='高' count='95' name='yes'><word>高</word><word>高い</word></match>
<match characters='切断' count='94'><word>切断</word></match>
<match characters='怖' count='94'><word>怖</word><word>怖い</word></match>
<match characters='振り返' count='94'><word>振り返す</word><word>振り返る</word></match>
<match characters='早' count='94' name='yes'><word>早</word><word>早い</word></match>
<match characters='明らか' count='94'><word>明らか</word></match>
<match characters='立派' count='94'><word>立派</word></match>
<match characters='１日' count='94'><word>１日</word></match>
<match characters='七' count='93' name='yes'><word>七</word></match>
<match characters='利き' count='93'><word>利き</word></match>
<match characters='根拠' count='93'><word>根拠</word></match>
<match characters='深' count='93' name='yes'><word>深</word><word>深い</word></match>
<match characters='理由' count='93' name='yes'><word>理由</word></match>
<match characters='許' count='93' name='yes'><word>許</word><word>許す</word></match>
<match characters='使' count='92' name='yes'><word>使</word><word>使う</word><word>使む</word></match>
<match characters='現れ' count='92'><word>現れ</word><word>現れる</word></match>
<match characters='疑問' count='92'><word>疑問</word></match>
<match characters='加藤' count='91' name='yes'></match>
<match characters='完' count='91' name='yes'><word>完</word></match>
<match characters='井山裕太' count='90' name='yes'></match>
<match characters='初' count='90' name='yes'><word>初</word></match>
<match characters='石井' count='90' name='yes'></match>
<match characters='連打' count='90'><word>連打</word></match>
<match characters='一番' count='89' name='yes'><word>一番</word></match>
<match characters='九' count='89' name='yes'><word>九</word></match>
<match characters='失' count='89'><word>失う</word></match>
<match characters='持ち' count='89'><word>持ち</word></match>
<match characters='何か' count='88'><word>何か</word></match>
<match characters='何も' count='88'><word>何も</word></match>
<match characters='勢' count='88' name='yes'><word>勢</word><word>勢む</word></match>
<match characters='振り' count='88'><word>振り</word></match>
<match characters='最強' count='88'><word>最強</word></match>
<match characters='白石' count='88' name='yes'><word>白石</word></match>
<match characters='一眼' count='87'><word>一眼</word></match>
<match characters='挑戦権' count='87'><word>挑戦権</word></match>
<match characters='確定' count='87'><word>確定</word></match>
<match characters='開始' count='87'><word>開始</word></match>
<match characters='世界' count='86' name='yes'><word>世界</word></match>
<match characters='争' count='86'><word>争う</word></match>