<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE root [
<!ELEMENT root (match*)>
<!ELEMENT match (word*)>
<!ATTLIST match characters CDATA #REQUIRED>
<!ATTLIST match count CDATA #REQUIRED>
<!ATTLIST match name (yes|no) "no">
<!ELEMENT word (#PCDATA)>
]>
<root>
<match characters='日' count='4334' name='yes'><word>日</word></match>
<match characters='月' count='3968' name='yes'><word>月</word></match>
<match characters='囲碁' count='3063'><word>囲碁</word></match>
<match characters='日本棋院' count='2475'><word>日本棋院</word></match>
<match characters='戦' count='2222' name='yes'><word>戦</word><word>戦う</word><word>戦く</word><word>戦ぐ</word></match>
<match characters='時' count='1944' name='yes'><word>時</word></match>
<match characters='第' count='1793'><word>第</word></match>
<match characters='級' count='1651'><word>級</word></match>
<match characters='大会' count='1415'><word>大会</word></match>
<match characters='年' count='1370' name='yes'><word>年</word></match>
<match characters='円' count='1260' name='yes'><word>円</word><word>円い</word></match>
<match characters='対局' count='1142'><word>対局</word></match>
<match characters='位' count='1108' name='yes'><word>位</word></match>
<match characters='参加' count='1101'><word>参加</word></match>
<match characters='回' count='1097' name='yes'><word>回</word><word>回す</word><word>回る</word></match>
<match characters='会' count='1007' name='yes'><word>会</word><word>会う</word><word>会す</word></match>
<match characters='方' count='923' name='yes'><word>方</word></match>
<match characters='分' count='918' name='yes'><word>分</word><word>分つ</word><word>分る</word></match>
<match characters='九段' count='864' name='yes'><word>九段</word></match>
<match characters='申し込み' count='766'><word>申し込み</word></match>
<match characters='勝' count='739' name='yes'><word>勝</word><word>勝つ</word><word>勝る</word></match>
<match characters='中' count='705' name='yes'><word>中</word><word>中る</word></match>
<match characters='局' count='700' name='yes'><word>局</word></match>
<match characters='棋士' count='697'><word>棋士</word></match>
<match characters='開催' count='696'><word>開催</word></match>
<match characters='解説' count='658'><word>解説</word></match>
<match characters='名' count='648' name='yes'><word>名</word></match>
<match characters='賞' count='643' name='yes'><word>賞</word></match>
<match characters='講師' count='638'><word>講師</word></match>
<match characters='八重洲' count='636' name='yes'></match>
<match characters='東京' count='622' name='yes'><word>東京</word></match>
<match characters='杯' count='603'><word>杯</word></match>
<match characters='東京都' count='601' name='yes'><word>東京都</word></match>
<match characters='場合' count='583' name='yes'><word>場合</word></match>
<match characters='様' count='553' name='yes'><word>様</word></match>
<match characters='認定' count='546'><word>認定</word></match>
<match characters='棋聖' count='534'><word>棋聖</word></match>
<match characters='六段' count='532'><word>六段</word></match>
<match characters='初段' count='521'><word>初段</word></match>
<match characters='場' count='510' name='yes'><word>場</word></match>
<match characters='会員' count='506'><word>会員</word></match>
<match characters='間' count='501' name='yes'><word>間</word></match>
<match characters='受付' count='500'><word>受付</word></match>
<match characters='平成' count='497' name='yes'><word>平成</word></match>
<match characters='申込' count='491'><word>申込</word><word>申込む</word></match>
<match characters='四段' count='481'><word>四段</word></match>
<match characters='市ヶ谷' count='476' name='yes'></match>
<match characters='応募' count='463'><word>応募</word></match>
<match characters='詳細' count='454'><word>詳細</word></match>
<match characters='開始' count='449'><word>開始</word></match>
<match characters='免状' count='441'><word>免状</word></match>
<match characters='段' count='440' name='yes'><word>段</word></match>
<match characters='優勝' count='422'><word>優勝</word></match>
<match characters='電話' count='422'><word>電話</word></match>
<match characters='期' count='421' name='yes'><word>期</word><word>期す</word></match>
<match characters='無料' count='418'><word>無料</word></match>
<match characters='碁' count='404'><word>碁</word></match>
<match characters='五段' count='397'><word>五段</word></match>
<match characters='者' count='396'><word>者</word></match>
<match characters='幽玄' count='384' name='yes'><word>幽玄</word></match>
<match characters='名人戦' count='376'><word>名人戦</word></match>
<match characters='金' count='376' name='yes'><word>金</word></match>
<match characters='階' count='373' name='yes'><word>階</word></match>
<match characters='会場' count='365' name='yes'><word>会場</word></match>
<match characters='大盤' count='362' name='yes'><word>大盤</word></match>
<match characters='情報' count='362'><word>情報</word></match>
<match characters='目' count='359' name='yes'><word>目</word><word>目す</word></match>
<match characters='部' count='359' name='yes'><word>部</word></match>
<match characters='各' count='355' name='yes'><word>各</word></match>
<match characters='棋力' count='354'><word>棋力</word></match>
<match characters='会館' count='353'><word>会館</word></match>
<match characters='予定' count='348'><word>予定</word></match>
<match characters='午前' count='345'><word>午前</word></match>
<match characters='土' count='345' name='yes'><word>土</word></match>
<match characters='当日' count='344' name='yes'><word>当日</word></match>
<match characters='八段' count='343' name='yes'><word>八段</word></match>
<match characters='敗' count='337'><word>敗</word><word>敗る</word></match>
<match characters='二段' count='336' name='yes'><word>二段</word></match>
<match characters='回戦' count='336'><word>回戦</word></match>
<match characters='講座' count='328'><word>講座</word></match>
<match characters='参加費' count='327'><word>参加費</word></match>
<match characters='方法' count='325'><word>方法</word></match>
<match characters='抽選' count='324'><word>抽選</word></match>
<match characters='下記' count='322'><word>下記</word></match>
<match characters='七段' count='317'><word>七段</word></match>
<match characters='下さい' count='315'><word>下さい</word></match>
<match characters='入門' count='314' name='yes'><word>入門</word></match>
<match characters='主催' count='306'><word>主催</word></match>
<match characters='本因坊' count='304' name='yes'><word>本因坊</word></match>
<match characters='本院' count='303'><word>本院</word></match>
<match characters='全国大会' count='299'><word>全国大会</word></match>
<match characters='申請' count='297'><word>申請</word></match>
<match characters='宝' count='296' name='yes'><word>宝</word></match>
<match characters='行われ' count='296'><word>行われる</word></match>
<match characters='酒造' count='291' name='yes'><word>酒造</word></match>
<match characters='公開' count='289'><word>公開</word></match>
<match characters='午後' count='283'><word>午後</word></match>
<match characters='参加者' count='279'><word>参加者</word></match>
<match characters='指導碁' count='278'><word>指導碁</word></match>
<match characters='代表' count='275'><word>代表</word></match>
<match characters='木' count='275' name='yes'><word>木</word></match>
<match characters='選手' count='275'><word>選手</word></match>
<match characters='以上' count='274'><word>以上</word></match>
<match characters='申込み' count='274'><word>申込み</word></match>
<match characters='三段' count='270' name='yes'><word>三段</word></match>
<match characters='名人' count='269' name='yes'><word>名人</word></match>
<match characters='人' count='267' name='yes'><word>人</word></match>
<match characters='半' count='259' name='yes'><word>半</word></match>
<match characters='普及' count='258'><word>普及</word></match>
<match characters='招待' count='253'><word>招待</word></match>
<match characters='案内' count='248' name='yes'><word>案内</word></match>
<match characters='支部' count='247' name='yes'><word>支部</word></match>
<match characters='行い' count='246'><word>行い</word></match>
<match characters='女流' count='239'><word>女流</word></match>
<match characters='勝負' count='238' name='yes'><word>勝負</word></match>
<match characters='事業部' count='237'><word>事業部</word></match>
<match characters='等' count='237' name='yes'><word>等</word></match>
<match characters='優勝者' count='234'><word>優勝者</word></match>
<match characters='時間' count='234' name='yes'><word>時間</word></match>
<match characters='お楽しみ' count='232'><word>お楽しみ</word></match>
<match characters='以外' count='231'><word>以外</word></match>
<match characters='皆様' count='231'><word>皆様</word></match>
<match characters='募集' count='230'><word>募集</word></match>
<match characters='個人情報' count='227'><word>個人情報</word></match>
<match characters='昼食' count='227'><word>昼食</word></match>
<match characters='本' count='225' name='yes'><word>本</word></match>
<match characters='張' count='222' name='yes'><word>張</word><word>張る</word></match>
<match characters='院生' count='219'><word>院生</word></match>
<match characters='教室' count='218'><word>教室</word></match>
<match characters='係' count='216' name='yes'><word>係</word><word>係う</word><word>係る</word></match>
<match characters='ご覧ください' count='215'><word>ご覧ください</word></match>
<match characters='住所' count='215' name='yes'><word>住所</word></match>
<match characters='表' count='215' name='yes'><word>表</word><word>表す</word></match>
<match characters='お問い合わせ' count='212'><word>お問い合わせ</word></match>
<match characters='互先' count='212'><word>互先</word></match>
<match characters='水' count='211' name='yes'><word>水</word></match>
<match characters='以下' count='209'><word>以下</word></match>
<match characters='記入' count='209'><word>記入</word></match>
<match characters='使用' count='206'><word>使用</word></match>
<match characters='定員' count='206'><word>定員</word></match>
<match characters='栩' count='205' name='yes'></match>
<match characters='お知らせ' count='203'><word>お知らせ</word></match>
<match characters='先番' count='201'><word>先番</word></match>
<match characters='氏名' count='201'><word>氏名</word></match>
<match characters='先' count='200' name='yes'><word>先</word></match>
<match characters='料' count='200'><word>料</word></match>
<match characters='希望' count='197' name='yes'><word>希望</word></match>
<match characters='団体戦' count='196'><word>団体戦</word></match>
<match characters='出場' count='194' name='yes'><word>出場</word></match>
<match characters='予選' count='193'><word>予選</word></match>
<match characters='参加資格' count='193'><word>参加資格</word></match>
<match characters='特別' count='192'><word>特別</word></match>
<match characters='コミ出し' count='191'><word>コミ出し</word></match>
<match characters='上' count='190' name='yes'><word>上</word><word>上す</word><word>上る</word></match>
<match characters='予想' count='190'><word>予想</word></match>
<match characters='選手権' count='189'><word>選手権</word></match>
<match characters='世界' count='188' name='yes'><word>世界</word></match>
<match characters='千代田区' count='186' name='yes'></match>
<match characters='序列' count='184'><word>序列</word></match>
<match characters='中学校' count='183'><word>中学校</word></match>
<match characters='電話番号' count='181'><word>電話番号</word></match>
<match characters='全国' count='180'><word>全国</word></match>
<match characters='火' count='180'><word>火</word></match>
<match characters='地下鉄' count='179'><word>地下鉄</word></match>
<match characters='贈呈' count='179'><word>贈呈</word></match>
<match characters='リーグ戦' count='175'><word>リーグ戦</word></match>
<match characters='内容' count='175'><word>内容</word></match>
<match characters='七番' count='174' name='yes'></match>
<match characters='決勝' count='174'><word>決勝</word></match>
<match characters='名様' count='172'><word>名様</word></match>
<match characters='大和証券' count='172' name='yes'></match>
<match characters='待ち' count='171'><word>待ち</word></match>
<match characters='打' count='171'><word>打</word><word>打つ</word></match>
<match characters='準優勝' count='171'><word>準優勝</word></match>
<match characters='連盟' count='170'><word>連盟</word></match>
<match characters='締切' count='169'><word>締切</word><word>締切る</word></match>
<match characters='全勝' count='168' name='yes'><word>全勝</word></match>
<match characters='取得' count='168'><word>取得</word></match>
<match characters='挑戦手合' count='166'><word>挑戦手合</word></match>
<match characters='日時' count='165'><word>日時</word></match>
<match characters='下車' count='164'><word>下車</word></match>
<match characters='実施' count='164'><word>実施</word></match>
<match characters='中継' count='163' name='yes'><word>中継</word></match>
<match characters='成績' count='163'><word>成績</word></match>
<match characters='持ち時間' count='163'><word>持ち時間</word></match>
<match characters='北海道' count='162' name='yes'><word>北海道</word></match>
<match characters='路盤' count='160'><word>路盤</word></match>
<match characters='状' count='159'><word>状</word></match>
<match characters='全員' count='158'><word>全員</word></match>
<match characters='学校' count='158' name='yes'><word>学校</word></match>
<match characters='料金' count='158'><word>料金</word></match>
<match characters='結果' count='157' name='yes'><word>結果</word></match>
<match characters='決定戦' count='156'><word>決定戦</word></match>
<match characters='歳' count='154' name='yes'><word>歳</word></match>
<match characters='中学生' count='153'><word>中学生</word></match>
<match characters='五番町' count='153' name='yes'></match>
<match characters='内' count='152' name='yes'><word>内</word></match>
<match characters='株式会社' count='152'><word>株式会社</word></match>
<match characters='提供' count='151'><word>提供</word></match>
<match characters='別' count='150' name='yes'><word>別</word><word>別つ</word></match>
<match characters='負け' count='150'><word>負け</word><word>負ける</word></match>
<match characters='中部総本部' count='149'><word>中部総本部</word></match>
<match characters='半額' count='149'><word>半額</word></match>
<match characters='法人' count='149' name='yes'><word>法人</word></match>
<match characters='郵送' count='149'><word>郵送</word></match>
<match characters='協賛' count='148'><word>協賛</word></match>
<match characters='扇子' count='148' name='yes'><word>扇子</word></match>
<match characters='本因坊戦' count='145'><word>本因坊戦</word></match>
<match characters='棋譜' count='145'><word>棋譜</word></match>
<match characters='聞き手' count='145'><word>聞き手</word></match>
<match characters='掲載' count='142'><word>掲載</word></match>
<match characters='高校' count='142' name='yes'><word>高校</word></match>
<match characters='明記' count='140' name='yes'><word>明記</word></match>
<match characters='決定' count='140'><word>決定</word></match>
<match characters='中国' count='139' name='yes'><word>中国</word></match>
<match characters='動画' count='139'><word>動画</word></match>
<match characters='後' count='139' name='yes'><word>後</word></match>
<match characters='に関する' count='138'><word>に関する</word></match>
<match characters='解' count='138' name='yes'><word>解</word><word>解く</word><word>解す</word><word>解る</word></match>
<match characters='詰碁' count='136'><word>詰碁</word></match>
<match characters='年齢' count='135'><word>年齢</word></match>
<match characters='段位' count='135'><word>段位</word></match>
<match characters='利用' count='134' name='yes'><word>利用</word></match>
<match characters='対象' count='134'><word>対象</word></match>
<match characters='記念' count='134'><word>記念</word></match>
<match characters='一般' count='133'><word>一般</word></match>
<match characters='問題' count='133'><word>問題</word></match>
<match characters='天元' count='131' name='yes'><word>天元</word></match>
<match characters='関西総本部' count='131'><word>関西総本部</word></match>
<match characters='四' count='130' name='yes'><word>四</word></match>
<match characters='子' count='130' name='yes'><word>子</word></match>
<match characters='決勝戦' count='130'><word>決勝戦</word></match>
<match characters='付き' count='129'><word>付き</word></match>
<match characters='井山裕太' count='128' name='yes'></match>
<match characters='碁聖' count='128'><word>碁聖</word></match>
<match characters='時半' count='127'><word>時半</word></match>
<match characters='駅' count='127' name='yes'><word>駅</word></match>
<match characters='問い合わせ' count='126'><word>問い合わせ</word><word>問い合わせる</word></match>
<match characters='所' count='126' name='yes'><word>所</word></match>
<match characters='時間切れ' count='126'><word>時間切れ</word></match>
<match characters='日曜日' count='125'><word>日曜日</word></match>
<match characters='勝ち' count='124'><word>勝ち</word></match>
<match characters='対' count='124' name='yes'><word>対</word><word>対う</word><word>対す</word></match>
<match characters='連勝' count='124'><word>連勝</word></match>
<match characters='徒歩' count='123'><word>徒歩</word></match>
<match characters='小学生' count='122'><word>小学生</word></match>
<match characters='山下' count='122' name='yes'></match>
<match characters='終了' count='122'><word>終了</word></match>
<match characters='関東' count='122' name='yes'><word>関東</word></match>
<match characters='競技' count='119'><word>競技</word></match>
<match characters='申込書' count='118'><word>申込書</word></match>
<match characters='因' count='117' name='yes'><word>因</word><word>因む</word><word>因る</word></match>
<match characters='問合せ' count='116'><word>問合せ</word><word>問合せる</word></match>
<match characters='説' count='116' name='yes'><word>説</word><word>説く</word></match>
<match characters='坊' count='115' name='yes'><word>坊</word></match>
<match characters='白' count='115' name='yes'><word>白</word><word>白い</word><word>白む</word></match>
<match characters='費' count='115' name='yes'><word>費</word></match>
<match characters='号' count='114' name='yes'><word>号</word></match>
<match characters='点' count='113' name='yes'><word>点</word><word>点く</word><word>点す</word><word>点る</word></match>
<match characters='井山' count='112' name='yes'></match>
<match characters='全' count='112' name='yes'><word>全</word></match>
<match characters='公益財団' count='112'><word>公益財団</word></match>
<match characters='手合' count='112' name='yes'><word>手合</word></match>
<match characters='催' count='111' name='yes'><word>催す</word></match>
<match characters='所属' count='111'><word>所属</word></match>
<match characters='参' count='110' name='yes'><word>参</word><word>参る</word></match>
<match characters='審判長' count='110'><word>審判長</word></match>
<match characters='加' count='109' name='yes'><word>加</word></match>
<match characters='科学' count='109'><word>科学</word></match>
<match characters='全額' count='108'><word>全額</word></match>
<match characters='前夜祭' count='108'><word>前夜祭</word></match>
<match characters='入場料' count='107'><word>入場料</word></match>
<match characters='十段' count='107'><word>十段</word></match>
<match characters='回文' count='107'><word>回文</word></match>
<match characters='大臣' count='107' name='yes'><word>大臣</word></match>
<match characters='大阪' count='107' name='yes'><word>大阪</word></match>
<match characters='来場' count='107' name='yes'><word>来場</word></match>
<match characters='祝' count='107' name='yes'><word>祝</word><word>祝う</word><word>祝す</word></match>
<match characters='変則' count='106'><word>変則</word></match>
<match characters='差' count='106'><word>差</word><word>差す</word></match>
<match characters='日本' count='106' name='yes'><word>日本</word></match>
<match characters='広島' count='105' name='yes'><word>広島</word></match>
<match characters='事務局' count='103'><word>事務局</word></match>
<match characters='名誉' count='103'><word>名誉</word></match>
<match characters='大' count='103' name='yes'><word>大</word></match>
<match characters='少年少女' count='103'><word>少年少女</word></match>
<match characters='変更' count='102'><word>変更</word></match>
<match characters='選手権大会' count='102'><word>選手権大会</word></match>
<match characters='地区' count='101'><word>地区</word></match>
<match characters='第１' count='101'><word>第１</word></match>
<match characters='手' count='100' name='yes'><word>手</word></match>
<match characters='県' count='100' name='yes'><word>県</word></match>
<match characters='入場' count='99' name='yes'><word>入場</word></match>
<match characters='指導' count='99'><word>指導</word></match>
<match characters='最新' count='99'><word>最新</word></match>
<match characters='三' count='98' name='yes'><word>三</word></match>
<match characters='個人戦' count='98'><word>個人戦</word></match>
<match characters='力' count='98' name='yes'><word>力</word><word>力む</word></match>
<match characters='開場' count='98' name='yes'><word>開場</word></match>
<match characters='当選者' count='97'><word>当選者</word></match>
<match characters='必着' count='97'><word>必着</word></match>
<match characters='文化' count='97' name='yes'><word>文化</word></match>
<match characters='以降' count='96'><word>以降</word></match>
<match characters='同' count='96' name='yes'><word>同</word></match>
<match characters='員' count='96' name='yes'><word>員</word></match>
<match characters='運営' count='96'><word>運営</word></match>
<match characters='先着' count='95'><word>先着</word></match>
<match characters='口' count='95' name='yes'><word>口</word></match>
<match characters='問' count='95' name='yes'><word>問</word><word>問う</word></match>
<match characters='王座' count='95' name='yes'><word>王座</word></match>
<match characters='関西' count='95' name='yes'><word>関西</word></match>
<match characters='往復' count='94'><word>往復</word></match>
<match characters='用紙' count='94'><word>用紙</word></match>
<match characters='発表' count='94'><word>発表</word></match>
<match characters='組' count='94' name='yes'><word>組</word><word>組む</word></match>
<match characters='定' count='93' name='yes'></match>
<match characters='日程' count='93'><word>日程</word></match>
<match characters='車' count='93' name='yes'><word>車</word></match>
<match characters='京都' count='92' name='yes'><word>京都</word></match>
<match characters='可' count='92' name='yes'><word>可</word></match>
<match characters='地域' count='92'><word>地域</word></match>
<match characters='必ず' count='92'><word>必ず</word></match>
<match characters='校' count='92' name='yes'><word>校</word></match>
<match characters='第３' count='92'><word>第３</word></match>
<match characters='ご了承' count='91'><word>ご了承</word></match>
<match characters='ご連絡' count='91'><word>ご連絡</word></match>
<match characters='割' count='91' name='yes'><word>割</word><word>割く</word><word>割る</word></match>
<match characters='碁盤' count='91' name='yes'><word>碁盤</word></match>
<match characters='主' count='90' name='yes'><word>主</word></match>
<match characters='意' count='90' name='yes'><word>意</word></match>
<match characters='ご用' count='89'><word>ご用</word></match>
<match characters='小' count='89' name='yes'><word>小</word><word>小い</word></match>
<match characters='棋戦' count='89'><word>棋戦</word></match>
<match characters='期間' count='88'><word>期間</word></match>
<match characters='事前' count='87'><word>事前</word></match>
<match characters='今回' count='87'><word>今回</word></match>
<match characters='件' count='87' name='yes'><word>件</word></match>
<match characters='奈留美' count='87' name='yes'></match>
<match characters='平日' count='87' name='yes'><word>平日</word></match>
<match characters='放送' count='87'><word>放送</word></match>
<match characters='付' count='86' name='yes'><word>付</word><word>付く</word><word>付す</word></match>
<match characters='団体' count='86' name='yes'><word>団体</word></match>
<match characters='女子' count='86' name='yes'><word>女子</word></match>
<match characters='目指し' count='86'><word>目指し</word></match>
<match characters='特典' count='85'><word>特典</word></match>
<match characters='税込' count='85'><word>税込</word></match>
<match characters='解説者' count='85'><word>解説者</word></match>
<match characters='勝敗' count='84'><word>勝敗</word></match>
<match characters='三位' count='83' name='yes'><word>三位</word></match>
<match characters='日記' count='83' name='yes'><word>日記</word></match>
<match characters='朝日' count='83' name='yes'><word>朝日</word><word>朝日る</word></match>
<match characters='行' count='83' name='yes'><word>行</word><word>行う</word><word>行く</word><word>行る</word></match>
<match characters='関西棋院' count='83' name='yes'><word>関西棋院</word></match>
<match characters='各自' count='82'><word>各自</word></match>
<match characters='含' count='82'><word>含む</word></match>
<match characters='登録' count='82'><word>登録</word></match>
<match characters='第２' count='82'><word>第２</word></match>
<match characters='同じ' count='81'><word>同じ</word><word>同じる</word></match>
<match characters='山田' count='81' name='yes'></match>
<match characters='模様' count='81'><word>模様</word></match>
<match characters='入会' count='80' name='yes'><word>入会</word></match>
<match characters='可能' count='80' name='yes'><word>可能</word></match>
<match characters='封じ手' count='80'><word>封じ手</word></match>
<match characters='山下敬吾' count='80' name='yes'></match>
<match characters='男子' count='80'><word>男子</word></match>
<match characters='盤' count='80' name='yes'><word>盤</word></match>
<match characters='程' count='80' name='yes'><word>程</word></match>
<match characters='締め切り' count='80'><word>締め切り</word></match>
<match characters='項' count='80' name='yes'><word>項</word></match>
<match characters='高等学校' count='80'><word>高等学校</word></match>
<match characters='下坂' count='79' name='yes'><word>下坂</word></match>
<match characters='必要事' count='79'><word>必要事</word></match>
<match characters='挑戦' count='79'><word>挑戦</word></match>
<match characters='福岡' count='79' name='yes'><word>福岡</word></match>
<match characters='週刊' count='79'><word>週刊</word></match>
<match characters='万波' count='78' name='yes'></match>
<match characters='全日本' count='78'><word>全日本</word></match>
<match characters='土曜日' count='78'><word>土曜日</word></match>
<match characters='毎週' count='78'><word>毎週</word></match>
<match characters='田中' count='78' name='yes'></match>
<match characters='紹介' count='78'><word>紹介</word></match>
<match characters='楽し' count='77'><word>楽しい</word><word>楽しむ</word></match>
<match characters='獲得' count='77'><word>獲得</word></match>
<match characters='神奈川' count='77' name='yes'></match>
<match characters='観戦' count='77'><word>観戦</word></match>
<match characters='込' count='77'><word>込む</word></match>
<match characters='高校生' count='77'><word>高校生</word></match>
<match characters='回目' count='76'><word>回目</word></match>
<match characters='次第' count='76'><word>次第</word></match>
<match characters='財' count='76' name='yes'><word>財</word></match>
<match characters='賞状' count='76'><word>賞状</word></match>
<match characters='必要' count='75'><word>必要</word></match>
<match characters='支援' count='75'><word>支援</word></match>
<match characters='数' count='75' name='yes'><word>数</word></match>
<match characters='朝日新聞社' count='75'><word>朝日新聞社</word></match>
<match characters='高尾紳路' count='75' name='yes'></match>
<match characters='佐藤' count='74' name='yes'></match>
<match characters='更新' count='74' name='yes'><word>更新</word></match>
<match characters='発売' count='74'><word>発売</word></match>
<match characters='聡' count='74' name='yes'><word>聡い</word></match>
<match characters='財団法人' count='74'><word>財団法人</word></match>
<match characters='都道府県' count='74'><word>都道府県</word></match>
<match characters='お客様' count='73'><word>お客様</word></match>
<match characters='典' count='73' name='yes'><word>典</word></match>
<match characters='多数' count='73'><word>多数</word></match>
<match characters='持' count='73' name='yes'><word>持つ</word></match>
<match characters='揮毫' count='73'><word>揮毫</word></match>
<match characters='向井' count='72' name='yes'></match>
<match characters='王' count='72' name='yes'><word>王</word></match>
<match characters='男女' count='72'><word>男女</word></match>
<match characters='競' count='72' name='yes'><word>競</word><word>競う</word><word>競る</word></match>
<match characters='賞品' count='72'><word>賞品</word></match>
<match characters='送り' count='72'><word>送り</word></match>
<match characters='選抜' count='72'><word>選抜</word></match>
<match characters='黒番' count='72'><word>黒番</word></match>
<match characters='保護者' count='71'><word>保護者</word></match>
<match characters='受講' count='71'><word>受講</word></match>
<match characters='問い合わせ先' count='71'><word>問い合わせ先</word></match>
<match characters='場所' count='71' name='yes'><word>場所</word></match>
<match characters='女性' count='71'><word>女性</word></match>
<match characters='美織' count='71' name='yes'></match>
<match characters='中園' count='70' name='yes'></match>
<match characters='及び' count='70'><word>及び</word></match>
<match characters='持ち' count='70'><word>持ち</word></match>
<match characters='有段者' count='70'><word>有段者</word></match>
<match characters='版' count='70'><word>版</word></match>
<match characters='目指' count='70'><word>目指</word><word>目指す</word></match>
<match characters='確認' count='70'><word>確認</word></match>
<match characters='社' count='70' name='yes'><word>社</word></match>
<match characters='銘' count='70' name='yes'><word>銘</word></match>
<match characters='林' count='69' name='yes'><word>林</word></match>
<match characters='生年月日' count='69'><word>生年月日</word></match>
<match characters='平岡' count='68' name='yes'></match>
<match characters='放映' count='68'><word>放映</word></match>
<match characters='昇級' count='68'><word>昇級</word></match>
<match characters='毎日新聞社' count='68' name='yes'><word>毎日新聞社</word></match>
<match characters='開会式' count='68'><word>開会式</word></match>
<match characters='お電話' count='67'><word>お電話</word></match>
<match characters='初' count='67' name='yes'><word>初</word></match>
<match characters='将棋' count='67'><word>将棋</word></match>
<match characters='愛知県' count='67' name='yes'><word>愛知県</word></match>
<match characters='梅沢由香里' count='67' name='yes'></match>
<match characters='現在' count='67'><word>現在</word></match>
<match characters='神奈川県' count='67' name='yes'><word>神奈川県</word></match>
<match characters='上位' count='66'><word>上位</word></match>
<match characters='中央区' count='66' name='yes'></match>
<match characters='大澤' count='66' name='yes'></match>
<match characters='好評' count='66'><word>好評</word></match>
<match characters='当選' count='66'><word>当選</word></match>
<match characters='彰' count='66' name='yes'></match>
<match characters='理事長' count='66' name='yes'><word>理事長</word></match>
<match characters='謝' count='66' name='yes'><word>謝す</word><word>謝る</word></match>
<match characters='道' count='66' name='yes'><word>道</word></match>
<match characters='上記' count='65'><word>上記</word></match>
<match characters='先着順' count='65'><word>先着順</word></match>
<match characters='勝ちと' count='65'><word>勝ちとる</word></match>
<match characters='式' count='65' name='yes'><word>式</word></match>
<match characters='復興' count='65'><word>復興</word></match>
<match characters='有料' count='65'><word>有料</word></match>
<match characters='面' count='65' name='yes'><word>面</word></match>