<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE root [
<!ELEMENT root (match*)>
<!ELEMENT match (word*)>
<!ATTLIST match characters CDATA #REQUIRED>
<!ATTLIST match count CDATA #REQUIRED>
<!ATTLIST match name (yes|no) "no">
<!ELEMENT word (#PCDATA)>
]>
<root>
<match characters='年' count='22981' name='yes'><word>年</word></match>
<match characters='囲碁' count='6953'><word>囲碁</word></match>
<match characters='戦' count='5961' name='yes'><word>戦</word><word>戦う</word><word>戦く</word><word>戦ぐ</word></match>
<match characters='編集' count='5046'><word>編集</word></match>
<match characters='杯' count='3745'><word>杯</word></match>
<match characters='月' count='3007' name='yes'><word>月</word></match>
<match characters='第' count='2977'><word>第</word></match>
<match characters='棋' count='2682'><word>棋</word></match>
<match characters='棋士' count='2465'><word>棋士</word></match>
<match characters='期' count='2249' name='yes'><word>期</word><word>期す</word></match>
<match characters='碁' count='2195'><word>碁</word></match>
<match characters='中国' count='2109' name='yes'><word>中国</word></match>
<match characters='回' count='2071' name='yes'><word>回</word><word>回す</word><word>回る</word></match>
<match characters='位' count='2057' name='yes'><word>位</word></match>
<match characters='日' count='2056' name='yes'><word>日</word></match>
<match characters='本因坊' count='1859' name='yes'><word>本因坊</word></match>
<match characters='優勝' count='1807'><word>優勝</word></match>
<match characters='目' count='1734' name='yes'><word>目</word><word>目す</word></match>
<match characters='勝' count='1731' name='yes'><word>勝</word><word>勝つ</word><word>勝る</word></match>
<match characters='日本棋院' count='1670'><word>日本棋院</word></match>
<match characters='棋戦' count='1541'><word>棋戦</word></match>
<match characters='囲' count='1492' name='yes'><word>囲う</word><word>囲む</word></match>
<match characters='世界' count='1444' name='yes'><word>世界</word></match>
<match characters='韓国' count='1444' name='yes'><word>韓国</word></match>
<match characters='王' count='1322' name='yes'><word>王</word></match>
<match characters='日本' count='1216' name='yes'><word>日本</word></match>
<match characters='外部リンク' count='1214'><word>外部リンク</word></match>
<match characters='黒' count='1206' name='yes'><word>黒</word><word>黒い</word><word>黒む</word></match>
<match characters='対局' count='1185'><word>対局</word></match>
<match characters='社' count='1144' name='yes'><word>社</word></match>
<match characters='白' count='1097' name='yes'><word>白</word><word>白い</word><word>白む</word></match>
<match characters='選手権' count='1045'><word>選手権</word></match>
<match characters='九段' count='1037' name='yes'><word>九段</word></match>
<match characters='李' count='1022' name='yes'><word>李</word></match>
<match characters='準優勝' count='1016'><word>準優勝</word></match>
<match characters='歳' count='956' name='yes'><word>歳</word></match>
<match characters='局' count='928' name='yes'><word>局</word></match>
<match characters='出場' count='925' name='yes'><word>出場</word></match>
<match characters='女流' count='907'><word>女流</word></match>
<match characters='将棋' count='881'><word>将棋</word></match>
<match characters='歴' count='878' name='yes'><word>歴</word><word>歴る</word></match>
<match characters='手' count='867' name='yes'><word>手</word></match>
<match characters='林' count='865' name='yes'><word>林</word></match>
<match characters='敗' count='856'><word>敗</word><word>敗る</word></match>
<match characters='名人' count='852' name='yes'><word>名人</word></match>
<match characters='名' count='792' name='yes'><word>名</word></match>
<match characters='張' count='790' name='yes'><word>張</word><word>張る</word></match>
<match characters='石' count='768' name='yes'><word>石</word></match>
<match characters='棋院' count='747'><word>棋院</word></match>
<match characters='優勝者' count='735'><word>優勝者</word></match>
<match characters='女子' count='724' name='yes'><word>女子</word></match>
<match characters='棋聖' count='715'><word>棋聖</word></match>
<match characters='時間' count='679' name='yes'><word>時間</word></match>
<match characters='七段' count='674'><word>七段</word></match>
<match characters='経歴' count='664'><word>経歴</word></match>
<match characters='打' count='661'><word>打</word><word>打つ</word></match>
<match characters='先番' count='660'><word>先番</word></match>
<match characters='人' count='658' name='yes'><word>人</word></match>
<match characters='目次' count='654' name='yes'><word>目次</word></match>
<match characters='場合' count='649' name='yes'><word>場合</word></match>
<match characters='名人戦' count='637'><word>名人戦</word></match>
<match characters='決勝' count='627'><word>決勝</word></match>
<match characters='中' count='621' name='yes'><word>中</word><word>中る</word></match>
<match characters='陳' count='610' name='yes'></match>
<match characters='挑戦者' count='609'><word>挑戦者</word></match>
<match characters='安井' count='605' name='yes'></match>
<match characters='朴' count='600' name='yes'><word>朴</word></match>
<match characters='井上' count='597' name='yes'></match>
<match characters='行われ' count='591'><word>行われる</word></match>
<match characters='五段' count='589'><word>五段</word></match>
<match characters='劉' count='582' name='yes'></match>
<match characters='者' count='580'><word>者</word></match>
<match characters='級' count='569'><word>級</word></match>
<match characters='因碩' count='557' name='yes'></match>
<match characters='八段' count='547' name='yes'><word>八段</word></match>
<match characters='参考文献' count='541'><word>参考文献</word></match>
<match characters='六段' count='540'><word>六段</word></match>
<match characters='門下' count='532' name='yes'><word>門下</word></match>
<match characters='同年' count='529'><word>同年</word></match>
<match characters='昇段' count='529'><word>昇段</word></match>
<match characters='負' count='528'><word>負</word><word>負う</word></match>
<match characters='白番' count='527'><word>白番</word></match>
<match characters='大会' count='518'><word>大会</word></match>
<match characters='主催' count='517'><word>主催</word></match>
<match characters='大' count='512' name='yes'><word>大</word></match>
<match characters='全国' count='508'><word>全国</word></match>
<match characters='天元' count='505' name='yes'><word>天元</word></match>
<match characters='所属' count='502'><word>所属</word></match>
<match characters='台湾' count='500' name='yes'><word>台湾</word></match>
<match characters='賞' count='477' name='yes'><word>賞</word></match>
<match characters='趙治勲' count='475' name='yes'></match>
<match characters='敗れ' count='474'><word>敗れ</word><word>敗れる</word></match>
<match characters='入り' count='473'><word>入り</word></match>
<match characters='勝負' count='473' name='yes'><word>勝負</word></match>
<match characters='家' count='473' name='yes'><word>家</word></match>
<match characters='会' count='467' name='yes'><word>会</word><word>会う</word><word>会す</word></match>
<match characters='相手' count='465'><word>相手</word></match>
<match characters='昌鎬' count='458' name='yes'></match>
<match characters='最強' count='448'><word>最強</word></match>
<match characters='新' count='447' name='yes'><word>新</word></match>
<match characters='本因坊戦' count='446'><word>本因坊戦</word></match>
<match characters='その他' count='445'><word>その他</word></match>
<match characters='東京' count='445' name='yes'><word>東京</word></match>
<match characters='関西棋院' count='439' name='yes'><word>関西棋院</word></match>
<match characters='行' count='437' name='yes'><word>行</word><word>行う</word><word>行く</word><word>行る</word></match>
<match characters='出身' count='428'><word>出身</word></match>
<match characters='薫鉉' count='427' name='yes'></match>
<match characters='呼ばれ' count='417'><word>呼ばれる</word></match>
<match characters='予選' count='410'><word>予選</word></match>
<match characters='その後' count='407'><word>その後</word></match>
<match characters='年度' count='404'><word>年度</word></match>
<match characters='放送' count='397'><word>放送</word></match>
<match characters='参加' count='396'><word>参加</word></match>
<match characters='星' count='396' name='yes'><word>星</word></match>
<match characters='入段' count='394'><word>入段</word></match>
<match characters='四段' count='392'><word>四段</word></match>
<match characters='傑' count='390' name='yes'></match>
<match characters='対抗' count='390'><word>対抗</word></match>
<match characters='時' count='390' name='yes'><word>時</word></match>
<match characters='獲得' count='390'><word>獲得</word></match>
<match characters='後' count='389' name='yes'><word>後</word></match>
<match characters='国際' count='388'><word>国際</word></match>
<match characters='王座' count='384' name='yes'><word>王座</word></match>
<match characters='小林光一' count='382' name='yes'></match>
<match characters='各' count='381' name='yes'><word>各</word></match>
<match characters='昭和' count='380' name='yes'><word>昭和</word></match>
<match characters='協会' count='378'><word>協会</word></match>
<match characters='方式' count='378'><word>方式</word></match>
<match characters='地' count='372' name='yes'><word>地</word></match>
<match characters='段' count='372' name='yes'><word>段</word></match>
<match characters='趙' count='370' name='yes'></match>
<match characters='徐' count='369' name='yes'></match>
<match characters='号' count='361' name='yes'><word>号</word></match>
<match characters='子' count='360' name='yes'><word>子</word></match>
<match characters='本' count='355' name='yes'><word>本</word></match>
<match characters='連覇' count='353'><word>連覇</word></match>
<match characters='分' count='351' name='yes'><word>分</word><word>分つ</word><word>分る</word></match>
<match characters='木谷' count='350' name='yes'></match>
<match characters='方円' count='345' name='yes'><word>方円</word></match>
<match characters='橋本' count='345' name='yes'></match>
<match characters='形' count='340' name='yes'><word>形</word></match>
<match characters='部' count='340' name='yes'><word>部</word></match>
<match characters='哲' count='337' name='yes'></match>
<match characters='リーグ戦' count='334'><word>リーグ戦</word></match>
<match characters='初' count='334' name='yes'><word>初</word></match>
<match characters='金' count='333' name='yes'><word>金</word></match>
<match characters='偉' count='331' name='yes'><word>偉</word><word>偉い</word></match>
<match characters='布石' count='331'><word>布石</word></match>
<match characters='初段' count='330'><word>初段</word></match>
<match characters='御城' count='329' name='yes'></match>
<match characters='記録' count='329' name='yes'><word>記録</word></match>
<match characters='呉清源' count='328' name='yes'></match>
<match characters='定石' count='327' name='yes'><word>定石</word></match>
<match characters='力' count='326' name='yes'><word>力</word><word>力む</word></match>
<match characters='日中' count='325' name='yes'><word>日中</word></match>
<match characters='決定戦' count='324'><word>決定戦</word></match>
<match characters='馬' count='323' name='yes'><word>馬</word></match>
<match characters='個人戦' count='321'><word>個人戦</word></match>
<match characters='北京' count='321' name='yes'><word>北京</word></match>
<match characters='坂田栄男' count='320' name='yes'></match>
<match characters='他' count='317'><word>他</word></match>
<match characters='成績' count='317'><word>成績</word></match>
<match characters='加藤正夫' count='316' name='yes'></match>
<match characters='古' count='315' name='yes'><word>古</word><word>古い</word><word>古す</word></match>
<match characters='図' count='314' name='yes'><word>図</word><word>図る</word></match>
<match characters='回戦' count='312'><word>回戦</word></match>
<match characters='引退' count='311'><word>引退</word></match>
<match characters='時に' count='311'><word>時に</word></match>
<match characters='受け' count='307'><word>受け</word><word>受ける</word></match>
<match characters='明治' count='307' name='yes'><word>明治</word></match>
<match characters='林海峰' count='307' name='yes'></match>
<match characters='決勝戦' count='305'><word>決勝戦</word></match>
<match characters='持' count='304' name='yes'><word>持つ</word></match>
<match characters='開催' count='303'><word>開催</word></match>
<match characters='栩' count='302' name='yes'></match>
<match characters='連勝' count='301'><word>連勝</word></match>
<match characters='代表' count='300'><word>代表</word></match>
<match characters='開始' count='300'><word>開始</word></match>
<match characters='多' count='296' name='yes'><word>多</word><word>多い</word></match>
<match characters='暁春' count='295' name='yes'></match>
<match characters='選手' count='295'><word>選手</word></match>
<match characters='上' count='294' name='yes'><word>上</word><word>上す</word><word>上る</word></match>
<match characters='界' count='294' name='yes'><word>界</word></match>
<match characters='呉' count='293' name='yes'></match>
<match characters='棋譜' count='293'><word>棋譜</word></match>
<match characters='依田紀基' count='291' name='yes'></match>
<match characters='常' count='290' name='yes'><word>常</word></match>
<match characters='点' count='290' name='yes'><word>点</word><word>点く</word><word>点す</word><word>点る</word></match>
<match characters='関連項目' count='290'><word>関連項目</word></match>
<match characters='女流棋士' count='288'><word>女流棋士</word></match>
<match characters='棋道' count='287'><word>棋道</word></match>
<match characters='昊' count='286' name='yes'></match>
<match characters='平成' count='285' name='yes'><word>平成</word></match>
<match characters='十段' count='284'><word>十段</word></match>
<match characters='進出' count='283' name='yes'><word>進出</word></match>
<match characters='半' count='282' name='yes'><word>半</word></match>
<match characters='歴代' count='281'><word>歴代</word></match>
<match characters='表記' count='280'><word>表記</word></match>
<match characters='聶' count='279' name='yes'></match>
<match characters='新人王' count='277'><word>新人王</word></match>
<match characters='設立' count='277'><word>設立</word></match>
<match characters='制' count='276' name='yes'><word>制</word><word>制す</word></match>
<match characters='三段' count='273' name='yes'><word>三段</word></match>
<match characters='大竹英雄' count='271' name='yes'></match>
<match characters='時代' count='271' name='yes'><word>時代</word></match>
<match characters='挑戦' count='270'><word>挑戦</word></match>
<match characters='賞金' count='270'><word>賞金</word></match>
<match characters='周' count='268' name='yes'><word>周</word></match>
<match characters='上海' count='266' name='yes'><word>上海</word></match>
<match characters='脚注' count='265'><word>脚注</word></match>
<match characters='後に' count='264'><word>後に</word></match>
<match characters='衛平' count='264' name='yes'></match>
<match characters='集' count='261' name='yes'><word>集</word><word>集う</word><word>集る</word></match>
<match characters='打っ' count='259'><word>打っ</word></match>
<match characters='二子' count='258' name='yes'><word>二子</word></match>
<match characters='当時' count='258' name='yes'><word>当時</word></match>
<match characters='碩' count='257' name='yes'></match>
<match characters='生まれ' count='255'><word>生まれ</word><word>生まれる</word></match>
<match characters='因' count='254' name='yes'><word>因</word><word>因む</word><word>因る</word></match>
<match characters='黄' count='250' name='yes'><word>黄</word></match>
<match characters='山下敬吾' count='247' name='yes'></match>
<match characters='元' count='246' name='yes'><word>元</word></match>
<match characters='崔' count='246' name='yes'></match>
<match characters='国手' count='245'><word>国手</word></match>
<match characters='挑戦手合' count='245'><word>挑戦手合</word></match>
<match characters='碁聖' count='245'><word>碁聖</word></match>
<match characters='秀策' count='244' name='yes'></match>
<match characters='謝' count='244' name='yes'><word>謝す</word><word>謝る</word></match>
<match characters='取' count='243' name='yes'><word>取</word><word>取る</word></match>
<match characters='団体戦' count='243'><word>団体戦</word></match>
<match characters='恩' count='243' name='yes'><word>恩</word></match>
<match characters='勝ち' count='242'><word>勝ち</word></match>
<match characters='二段' count='240' name='yes'><word>二段</word></match>
<match characters='詰碁' count='238'><word>詰碁</word></match>
<match characters='新鋭' count='237'><word>新鋭</word></match>
<match characters='甲' count='237' name='yes'><word>甲</word></match>
<match characters='数' count='236' name='yes'><word>数</word></match>
<match characters='世' count='235' name='yes'><word>世</word></match>
<match characters='春' count='235' name='yes'><word>春</word></match>
<match characters='項目' count='235'><word>項目</word></match>
<match characters='市' count='234' name='yes'><word>市</word></match>
<match characters='早碁' count='234'><word>早碁</word></match>
<match characters='多く' count='233'><word>多く</word></match>
<match characters='冠' count='232' name='yes'><word>冠</word><word>冠る</word></match>
<match characters='文化' count='232' name='yes'><word>文化</word></match>
<match characters='藤沢秀行' count='232' name='yes'></match>
<match characters='堂' count='230' name='yes'><word>堂</word></match>
<match characters='現在' count='230'><word>現在</word></match>
<match characters='隅' count='229' name='yes'><word>隅</word></match>
<match characters='オープン戦' count='226'><word>オープン戦</word></match>
<match characters='入門' count='226' name='yes'><word>入門</word></match>
<match characters='勲' count='226' name='yes'><word>勲</word></match>
<match characters='武宮正樹' count='223' name='yes'></match>
<match characters='男子' count='223'><word>男子</word></match>
<match characters='中央' count='221' name='yes'><word>中央</word></match>
<match characters='元年' count='221' name='yes'><word>元年</word></match>
<match characters='紹介' count='221'><word>紹介</word></match>
<match characters='道策' count='221' name='yes'></match>
<match characters='入' count='220' name='yes'><word>入</word><word>入る</word></match>
<match characters='以降' count='219'><word>以降</word></match>
<match characters='著作' count='219'><word>著作</word></match>
<match characters='院生' count='219'><word>院生</word></match>
<match characters='三番勝負' count='217'><word>三番勝負</word></match>
<match characters='秀栄' count='217' name='yes'></match>
<match characters='全日本' count='216'><word>全日本</word></match>
<match characters='番' count='216' name='yes'><word>番</word><word>番う</word><word>番る</word></match>
<match characters='父' count='215' name='yes'><word>父</word></match>
<match characters='曹' count='214' name='yes'></match>
<match characters='務め' count='213'><word>務め</word><word>務める</word></match>
<match characters='国' count='213' name='yes'><word>国</word></match>
<match characters='発売' count='213'><word>発売</word></match>
<match characters='藤沢' count='212' name='yes'></match>
<match characters='先' count='211' name='yes'><word>先</word></match>
<match characters='秀和' count='211' name='yes'></match>
<match characters='結果' count='211' name='yes'><word>結果</word></match>
<match characters='羽根直樹' count='211' name='yes'></match>
<match characters='現代' count='209' name='yes'><word>現代</word></match>
<match characters='勝利' count='208' name='yes'><word>勝利</word></match>
<match characters='十' count='204' name='yes'><word>十</word></match>
<match characters='丈和' count='203' name='yes'></match>
<match characters='省' count='203' name='yes'><word>省</word><word>省く</word></match>
<match characters='楊' count='202' name='yes'><word>楊</word></match>
<match characters='名誉' count='201'><word>名誉</word></match>
<match characters='盤' count='201' name='yes'><word>盤</word></match>
<match characters='四' count='200' name='yes'><word>四</word></match>
<match characters='宇太郎' count='200' name='yes'></match>
<match characters='洙' count='200' name='yes'></match>
<match characters='大手合' count='199'><word>大手合</word></match>
<match characters='翌年' count='199'><word>翌年</word></match>
<match characters='対戦' count='198'><word>対戦</word></match>
<match characters='持ち時間' count='198'><word>持ち時間</word></match>
<match characters='残' count='198' name='yes'><word>残</word><word>残す</word><word>残る</word></match>
<match characters='手合' count='197' name='yes'><word>手合</word></match>
<match characters='天保' count='196' name='yes'><word>天保</word></match>
<match characters='方' count='195' name='yes'><word>方</word></match>
<match characters='火災' count='195'><word>火災</word></match>
<match characters='破' count='195' name='yes'><word>破</word><word>破く</word><word>破る</word></match>
<match characters='銘' count='195' name='yes'><word>銘</word></match>
<match characters='仙角' count='194' name='yes'></match>
<match characters='以下' count='194'><word>以下</word></match>
<match characters='尹' count='194' name='yes'><word>尹</word></match>
<match characters='書' count='194'><word>書</word><word>書く</word></match>
<match characters='果た' count='194'><word>果たす</word></match>
<match characters='鈴木' count='194' name='yes'></match>
<match characters='受賞' count='193'><word>受賞</word></match>
<match characters='組' count='193' name='yes'><word>組</word><word>組む</word></match>
<match characters='富士通' count='190'><word>富士通</word></match>
<match characters='次' count='189' name='yes'><word>次</word><word>次ぐ</word></match>
<match characters='少年' count='188'><word>少年</word></match>
<match characters='石田芳夫' count='188' name='yes'></match>
<match characters='解説' count='188'><word>解説</word></match>
<match characters='創設' count='187'><word>創設</word></match>
<match characters='対' count='187' name='yes'><word>対</word><word>対う</word><word>対す</word></match>
<match characters='左' count='187' name='yes'><word>左</word></match>
<match characters='番組' count='187' name='yes'><word>番組</word></match>
<match characters='跡目' count='187'><word>跡目</word></match>
<match characters='打たれ' count='186'><word>打たれる</word></match>
<match characters='新聞' count='185' name='yes'><word>新聞</word></match>
<match characters='李世' count='185' name='yes'></match>
<match characters='決定' count='185'><word>決定</word></match>
<match characters='名の' count='184'><word>名のる</word></match>
<match characters='呼' count='184' name='yes'><word>呼ぶ</word></match>
<match characters='国内' count='184'><word>国内</word></match>
<match characters='永' count='184' name='yes'><word>永</word><word>永い</word></match>
<match characters='赫' count='184' name='yes'><word>赫う</word><word>赫く</word></match>
<match characters='史上' count='183'><word>史上</word></match>
<match characters='孔' count='183' name='yes'><word>孔</word></match>
<match characters='強' count='183' name='yes'><word>強</word><word>強い</word></match>
<match characters='採用試験' count='183'><word>採用試験</word></match>
<match characters='含' count='182'><word>含む</word></match>
<match characters='自分' count='181'><word>自分</word></match>
<match characters='記事' count='181'><word>記事</word></match>
<match characters='加藤' count='179' name='yes'></match>
<match characters='争' count='178'><word>争う</word></match>
<match characters='門入' count='178' name='yes'></match>
<match characters='兪' count='177' name='yes'></match>
<match characters='棋風' count='177'><word>棋風</word></match>
<match characters='全' count='176' name='yes'><word>全</word></match>
<match characters='書房' count='176'><word>書房</word></match>
<match characters='井山裕太' count='174' name='yes'></match>
<match characters='家元' count='172' name='yes'><word>家元</word></match>
<match characters='所' count='172' name='yes'><word>所</word></match>
<match characters='王立誠' count='172' name='yes'></match>
<match characters='用い' count='172'><word>用いる</word></match>
<match characters='誠文' count='172' name='yes'></match>
<match characters='負け' count='172'><word>負け</word><word>負ける</word></match>
<match characters='三星' count='170' name='yes'></match>
<match characters='十番碁' count='170'><word>十番碁</word></match>
<match characters='巻' count='170' name='yes'><word>巻</word><word>巻く</word></match>
<match characters='見' count='170' name='yes'><word>見</word><word>見す</word><word>見る</word></match>
<match characters='宋' count='169' name='yes'><word>宋</word></match>
<match characters='死去' count='169'><word>死去</word></match>
<match characters='新光' count='168' name='yes'></match>
<match characters='破り' count='168'><word>破り</word></match>
<match characters='高尾紳路' count='168' name='yes'></match>
<match characters='高校' count='168' name='yes'><word>高校</word></match>
<match characters='敗退' count='167'><word>敗退</word></match>
<match characters='斌' count='167' name='yes'></match>
<match characters='明' count='167' name='yes'><word>明</word><word>明い</word><word>明く</word><word>明る</word></match>
<match characters='講座' count='167'><word>講座</word></match>
<match characters='少年少女' count='166'><word>少年少女</word></match>
<match characters='等' count='166' name='yes'><word>等</word></match>
<match characters='主な' count='164'><word>主な</word></match>
<match characters='交流' count='164'><word>交流</word></match>
<match characters='例' count='164' name='yes'><word>例</word></match>
<match characters='奉' count='164' name='yes'><word>奉る</word></match>
<match characters='算知' count='164' name='yes'></match>
<match characters='団体' count='163' name='yes'><word>団体</word></match>
<match characters='碁盤' count='162' name='yes'><word>碁盤</word></match>
<match characters='結城聡' count='162' name='yes'></match>
<match characters='姜' count='161' name='yes'></match>
<match characters='表示' count='161'><word>表示</word></match>
<match characters='閲覧' count='161'><word>閲覧</word></match>
<match characters='歴史' count='160'><word>歴史</word></match>
<match characters='用語' count='160'><word>用語</word></match>
<match characters='秀' count='159' name='yes'><word>秀</word></match>
<match characters='達' count='159' name='yes'><word>達</word><word>達す</word></match>
<match characters='小光' count='158' name='yes'></match>
<match characters='戦績' count='158'><word>戦績</word></match>
<match characters='得' count='157' name='yes'><word>得</word><word>得る</word></match>
<match characters='昌赫' count='157' name='yes'></match>
<match characters='求め' count='157'><word>求め</word><word>求める</word></match>
<match characters='仙知' count='156' name='yes'></match>
<match characters='道' count='156' name='yes'><word>道</word></match>
<match characters='度' count='155' name='yes'><word>度</word></match>
<match characters='抜き' count='155'><word>抜き</word></match>
<match characters='模様' count='155'><word>模様</word></match>
<match characters='活躍' count='155'><word>活躍</word></match>
<match characters='瀬越' count='155' name='yes'></match>
<match characters='至' count='155' name='yes'><word>至</word><word>至る</word></match>
<match characters='上位' count='154'><word>上位</word></match>
<match characters='周俊' count='154' name='yes'></match>
<match characters='江戸時代' count='154'><word>江戸時代</word></match>
<match characters='安永' count='153' name='yes'><word>安永</word></match>
<match characters='手筋' count='153'><word>手筋</word></match>
<match characters='決め' count='153'><word>決め</word><word>決める</word></match>
<match characters='着手' count='153'><word>着手</word></match>
<match characters='立' count='153' name='yes'><word>立つ</word></match>
<match characters='一つ' count='152'><word>一つ</word></match>
<match characters='耀' count='152' name='yes'><word>耀う</word><word>耀く</word></match>
<match characters='秀甫' count='151' name='yes'></match>
<match characters='関連' count='151'><word>関連</word></match>
<match characters='段位' count='150'><word>段位</word></match>
<match characters='実力' count='149'><word>実力</word></match>
<match characters='関西' count='149' name='yes'><word>関西</word></match>
<match characters='先相先' count='148'><word>先相先</word></match>
<match characters='女流名人' count='148'><word>女流名人</word></match>
<match characters='招待' count='148'><word>招待</word></match>
<match characters='玄' count='148' name='yes'></match>
<match characters='知' count='148' name='yes'><word>知</word><word>知る</word></match>
<match characters='互先' count='147'><word>互先</word></match>
<match characters='秒読み' count='147'><word>秒読み</word></match>
<match characters='に対して' count='146'><word>に対して</word></match>
<match characters='以上' count='145'><word>以上</word></match>
<match characters='大阪' count='145' name='yes'><word>大阪</word></match>
<match characters='最年少' count='145'><word>最年少</word></match>
<match characters='祖' count='145' name='yes'><word>祖</word></match>
<match characters='隠' count='145' name='yes'><word>隠す</word><word>隠る</word></match>
<match characters='小林' count='144' name='yes'></match>
<match characters='高' count='144' name='yes'><word>高</word><word>高い</word></match>
<match characters='代' count='143' name='yes'><word>代</word><word>代る</word></match>
<match characters='以後' count='143' name='yes'><word>以後</word></match>
<match characters='各種' count='143'><word>各種</word></match>
<match characters='大元' count='143' name='yes'></match>
<match characters='小目' count='143' name='yes'><word>小目</word></match>
<match characters='岩本' count='143' name='yes'></match>
<match characters='秀哉' count='143' name='yes'></match>
<match characters='終了' count='143'><word>終了</word></match>
<match characters='対局者' count='142'><word>対局者</word></match>
<match characters='小林覚' count='142' name='yes'></match>
<match characters='本因坊秀哉' count='142' name='yes'></match>
<match characters='編' count='142' name='yes'><word>編</word><word>編む</word></match>
<match characters='認め' count='142'><word>認め</word><word>認める</word></match>
<match characters='雁金' count='142' name='yes'><word>雁金</word></match>
<match characters='幻庵' count='141' name='yes'></match>
<match characters='瀚' count='141' name='yes'></match>
<match characters='計' count='141' name='yes'><word>計</word><word>計る</word></match>
<match characters='鄭' count='141' name='yes'></match>
<match characters='奕' count='140'><word>奕</word></match>
<match characters='式' count='140' name='yes'><word>式</word></match>
<match characters='仙' count='139' name='yes'><word>仙</word></match>
<match characters='弟子' count='139' name='yes'><word>弟子</word></match>
<match characters='誌' count='139'><word>誌</word><word>誌す</word></match>
<match characters='七番' count='138' name='yes'></match>
<match characters='下' count='138' name='yes'><word>下</word><word>下す</word><word>下る</word></match>
<match characters='攻め' count='138'><word>攻め</word><word>攻める</word></match>
<match characters='文' count='138' name='yes'><word>文</word></match>
<match characters='瑩' count='138' name='yes'></match>
<match characters='享保' count='137' name='yes'><word>享保</word></match>
<match characters='前期' count='137'><word>前期</word></match>
<match characters='坂田' count='137' name='yes'></match>
<match characters='若手' count='137' name='yes'><word>若手</word></match>